routes:
  - [GET, /, Index->get]
  - [POST, /, Index->post]
  - [GET, /subpath#anchor, Index->get]
  - [POST, /subpath#anchor, Index->post]
  - [GET, /subpath/subpath, Index->get]
  - [POST, /subpath/subpath, Index->post]
  - [GET, /api, Index->api]
  - [GET, /(numeric)/(string), Index->get]
  - [POST, /(numeric)/(string), Index->post]
  - [GET, /(string)/(numeric)/subpath, Index->get]
  - [POST, /(string)/(numeric)/subpath, Index->post]
  - [GET, /(numeric)/(string)/subpath, Index->get]
  - [POST, /(numeric)/(string)/subpath, Index->post]
  - [GET, /subpath/(string)/(numeric), Index->get]
  - [POST, /subpath/(string)/(numeric), Index->post]
  - [GET, /subpath/(numeric)/(string)#anchor, Index->get]
  - [POST, /subpath/(numeric)/(string)#anchor, Index->post]

rest:
  - [CRUDL, /user, User]
  - [CRUDL, /group, Group]

fallback: Index->get

baseNamespace: TimTegeler\Routerunner
